### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by AmingWu** [allenai/savn#1]
Hello, when I run your code, there is an error. Could you give me some advice?

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from utils.class_finder import model_class, agent_class, optimizer_class
  File "/home/aming/savn/utils/class_finder.py", line 2, in <module>
    import agents
  File "/home/aming/savn/agents/__init__.py", line 2, in <module>
    from .random_agent import RandomNavigationAgent
  File "/home/aming/savn/agents/random_agent.py", line 6, in <module>
    from episodes.basic_episode import BasicEpisode
  File "/home/aming/savn/episodes/__init__.py", line 1, in <module>
    from .basic_episode import BasicEpisode
  File "/home/aming/savn/episodes/basic_episode.py", line 8, in <module>
    from datasets.environment import Environment
  File "/home/aming/savn/datasets/environment.py", line 7, in <module>
    from .offline_controller_with_small_rotation import OfflineControllerWithSmallRotation
  File "/home/aming/savn/datasets/offline_controller_with_small_rotation.py", line 653
    **self.grid[0], rotation=random.choice(self.rotations)

**Comment by mitchellnw** [comment]
Hi, are you able to post the full output from the run? I will then be able to better understand the issue.

**Comment by mitchellnw** [comment]
Closing this issue, please reopen if this is still an issue!
