### ISSUE TITLE
training time?

### ISSUE THREAD

**Issue by jet-yangqs** [allenai/savn#22]
Hi,
    How long will it take to train a model as good as your pretrained ones or achieve the result reported in readme?
   
               thank you~

**Comment by mitchellnw** [comment]
Around 2 days

**Comment by xuai05** [comment]
>Hello, when I call your search_and_save function, what is the cause of the following error? After the error occurs, the process becomes a zombie process, and the program cannot continue.

Traceback (most recent call last):
File "/home/ubuntu/miniconda3/envs/VT_Depth/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/home/ubuntu/miniconda3/envs/VT_Depth/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "gen_ground_truth.py", line 39, in search_and_save
c.start()
File "/home/ubuntu/miniconda3/envs/VT_Depth/lib/python3.6/site-packages/ai2thor/controller.py", line 804, in start
self.download_binary()
File "/home/ubuntu/miniconda3/envs/VT_Depth/lib/python3.6/site-packages/ai2thor/controller.py", line 742, in download_binary
os.rename(extract_dir, os.path.join(self.releases_dir(), self.build_name()))
OSError: [Errno 39] Directory not empty: '/home/ubuntu/.ai2thor/tmp/thor-201903131714-Linux64' -> '/home/ubuntu/.ai2thor/releases/thor-201903131714-Linux64'
