### ISSUE TITLE
RuntimeError when training the SAVN model

### ISSUE THREAD

**Issue by wupx99** [allenai/savn#23]
Hello，

Thanks for sharing the code. 

I encountered an error when training the SAVN model. Here are the commands I entered and the error message:
___________________________________________________________________________________________________________________
	(savn) wpx@avs:~/project/savn$ python main.py --title savn_train --model SAVN --gpu-ids 0 1 --workers 12
	initialized optimizer.
	attempting to share memory.
	sharing memory.
	SAVN(
	  (conv1): Conv2d(512, 64, kernel_size=(1, 1), stride=(1, 1))
	  (maxp1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
	  (embed_glove): Linear(in_features=300, out_features=64, bias=True)
	  (embed_action): Linear(in_features=6, out_features=10, bias=True)
	  (pointwise): Conv2d(138, 64, kernel_size=(1, 1), stride=(1, 1))
	  (lstm): LSTMCell(3136, 512)
	  (critic_linear): Linear(in_features=512, out_features=1, bias=True)
	  (actor_linear): Linear(in_features=512, out_features=6, bias=True)
	  (action_predict_linear): Linear(in_features=6272, out_features=6, bias=True)
	  (dropout): Dropout(p=0.25)
	  (ll_key): Linear(in_features=518, out_features=518, bias=True)
	  (ll_linear): Linear(in_features=518, out_features=518, bias=True)
	  (ll_tc): TemporalConvNet(
		(ll_temporal_block0): TemporalBlock(
		  (ll_conv1): Conv1d(6, 10, kernel_size=(2,), stride=(1,), padding=(1,))
		  (chomp1): Chomp1d()
		  (ll_conv2): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(1,))
		  (chomp2): Chomp1d()
		  (sigmoid): Sigmoid()
		)
		(ll_temporal_block1): TemporalBlock(
		  (ll_conv1): Conv1d(10, 1, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
		  (chomp1): Chomp1d()
		  (ll_conv2): Conv1d(1, 1, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
		  (chomp2): Chomp1d()
		  (sigmoid): Sigmoid()
		)
	  )
	)
	Train agents created.
	Process Process-2:
	Traceback (most recent call last):
	  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
		self.run()
	  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
		self._target(*self._args, **self._kwargs)
	  File "/home/wpx/project/savn/runners/savn_train.py", line 140, in savn_train
		transfer_gradient_to_shared(meta_gradient, shared_model, gpu_id)
	  File "/home/wpx/project/savn/runners/train_util.py", line 110, in transfer_gradient_to_shared
		param._grad = gradient[i].cpu()
	RuntimeError: assigned grad has data of a different size
____________________________________________________________________________________________________________

I have checked my gpu and cuda and they are all running normally. 

Any suggestions？Thanks.

**Comment by wupx99** [comment]
> 
> 
> Hello，
> 
> Thanks for sharing the code.
> 
> I encountered an error when training the SAVN model. Here are the commands I entered and the error message:
> 
> ```
> (savn) wpx@avs:~/project/savn$ python main.py --title savn_train --model SAVN --gpu-ids 0 1 --workers 12
> initialized optimizer.
> attempting to share memory.
> sharing memory.
> SAVN(
>   (conv1): Conv2d(512, 64, kernel_size=(1, 1), stride=(1, 1))
>   (maxp1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
>   (embed_glove): Linear(in_features=300, out_features=64, bias=True)
>   (embed_action): Linear(in_features=6, out_features=10, bias=True)
>   (pointwise): Conv2d(138, 64, kernel_size=(1, 1), stride=(1, 1))
>   (lstm): LSTMCell(3136, 512)
>   (critic_linear): Linear(in_features=512, out_features=1, bias=True)
>   (actor_linear): Linear(in_features=512, out_features=6, bias=True)
>   (action_predict_linear): Linear(in_features=6272, out_features=6, bias=True)
>   (dropout): Dropout(p=0.25)
>   (ll_key): Linear(in_features=518, out_features=518, bias=True)
>   (ll_linear): Linear(in_features=518, out_features=518, bias=True)
>   (ll_tc): TemporalConvNet(
> 	(ll_temporal_block0): TemporalBlock(
> 	  (ll_conv1): Conv1d(6, 10, kernel_size=(2,), stride=(1,), padding=(1,))
> 	  (chomp1): Chomp1d()
> 	  (ll_conv2): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(1,))
> 	  (chomp2): Chomp1d()
> 	  (sigmoid): Sigmoid()
> 	)
> 	(ll_temporal_block1): TemporalBlock(
> 	  (ll_conv1): Conv1d(10, 1, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
> 	  (chomp1): Chomp1d()
> 	  (ll_conv2): Conv1d(1, 1, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
> 	  (chomp2): Chomp1d()
> 	  (sigmoid): Sigmoid()
> 	)
>   )
> )
> Train agents created.
> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
> 	self.run()
>   File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
> 	self._target(*self._args, **self._kwargs)
>   File "/home/wpx/project/savn/runners/savn_train.py", line 140, in savn_train
> 	transfer_gradient_to_shared(meta_gradient, shared_model, gpu_id)
>   File "/home/wpx/project/savn/runners/train_util.py", line 110, in transfer_gradient_to_shared
> 	param._grad = gradient[i].cpu()
> RuntimeError: assigned grad has data of a different size
> ```
> 
> I have checked my gpu and cuda and they are all running normally.
> 
> Any suggestions？Thanks.

I found that the error is caused by the version of python. I have solved this problem by using python3.7.
